config/routes.rb
Rails.application.routes.draw do
  
  root to: 'application#welcome'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy' 
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  
  resources :companies
  resources :subscriptions
  
  resources :users do
    resources :subscriptions 
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/company.rb
class Company < ApplicationRecord
    has_many :subscriptions
    has_many :users, through: :subscriptions

    validates :name, presence: true

    scope :list_aplha, -> {joins(:subscriptions).group('companies.name').order('LOWER(name)')}

end

app/models/subscription.rb
class Subscription < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :company

    
    validates :amount_per_month, presence: true, numericality: { greater_than_or_equal_to: 0 }
    validates :type_of_subscription, presence: true

    def company_attributes=(company_attributes) 
        if !self.company_id
            self.company = Company.find_or_create_by(company_attributes)
        end
    end

    scope :list_by_amount, -> {joins(:company).group('subscriptions.amount_per_month').order('amount_per_month')}
    
    # queries all subscriptions of a specific user for index view
    def self.user_subscription_index(user) 
        @subscriptions = user.subscriptions.all
    end 
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :subscriptions, dependent: :destroy
  has_many :companies, through: :subscriptions

  # validates comes from active record NOT rails specific method. Can use this in any programming library useing active record
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
   
    def welcome
        if !logged_in?
            redirect_to login_path
        end
    end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  def index
    @companies = Company.list_aplha.all
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def destroy
    @company = Company.find_by_id(params[:id])
    @company.destroy
    redirect_to companies_path
  end

end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def delete
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    # Only going render login form - not creating any new obj
    def new
        if logged_in?
            redirect_to root_path
        end
    end

    # process login form
    def create
        user = User.find_by(username: params[:username])
        if user && user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to root_path
        else
          flash.now[:notice] =  "* Login Info Was Incorrect - Please Try Again *"
          render :new          
        end
    end

    # logout
    def destroy
        session.delete :user_id
        redirect_to login_path
    end

    def omniauth
        user = User.find_or_create_by(uid: request.env['omniauth.auth'][:uid], provider: request.env['omniauth.auth'][:provider]) do |u|
            u.username = request.env['omniauth.auth'][:info][:name]
            u.email = request.env['omniauth.auth'][:info][:email]
            u.password = SecureRandom.hex(15)
        end
        if user.valid?
            session[:user_id] = user.id
            redirect_to root_path
        else
            redirect_to login_path
        end
    end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :require_login
  before_action :set_subscription, except: [:index, :new, :create]

  # show all subscriptions route: '/subscriptions' path: subscriptions_path
  def index
    if params[:user_id]
      @subscriptions = Subscription.user_subscription_index(current_user).list_by_amount
    else
      @subscriptions = current_user.subscriptions
    end
    render action: "index", layout: "create_new_subscription"
  end

  # render a new form route: '/subscriptions/new' path: new_subscription_path
  def new
    @subscription = Subscription.new(user_id: params[:user_id])
    @company = @subscription.build_company

    render action: "new", layout: "all_users_subscriptions"
  end

  # process submitted new form route: '/subscriptions' POSTS to INDEX route path: subscriptions_path  -- only used on server side
  def create
    @subscription = current_user.subscriptions.build(subscription_params)
    @company = @subscription.company
    if @subscription.save && @company.valid?
      redirect_to user_subscription_path(current_user.username, @subscription)
    else
      #render preserves data to show user with hash of errors. redirect refreshes data
      render :new
    end
  end

  # render single subscription route: '/subscriptions/id' path: subscription_path(subscription_id)
  def show
    render action: "show", layout: "all_users_subscriptions"
  end

  def edit
    @company = @subscription.company
  end

  def update
    if @subscription.update(subscription_params)
      redirect_to user_subscription_path(current_user.username, @subscription)
    else
      flash.now[:notice] =  "* Please Complete ALL Fields *"
      render :edit
    end
  end

  def destroy
    @subscription.destroy
    redirect_to user_subscriptions_path(current_user.username)
  end

private

  # permits fields being submited
  def subscription_params
    params.require(:subscription).permit(:amount_per_month, :type_of_subscription, :user_id, :company_id, company_attributes: [:name])
  end

   # query donation table and pass in id - find obj
  def set_subscription
    @subscription = Subscription.find_by_id(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def index
    @users = User.all
  end

  # render signup form
  def new
    # instantiate an empty new user object to wrap(encapsulate) the login form around it
    if !logged_in?
      @user = User.new
    else
      redirect_to root  
    end
  end

  # resposible for proccesing signup form
  def create
    @user = User.new(user_params)
    if @user.save
      # log user in
      # [key] and set that to new users id
      session[:user_id] = @user.id
      redirect_to root_path
    else
      # show errors with validation errors
      # make them try again
      render :new
    end
  end


  def show
    @user = User.find_by_id(params[:id])
  end 

  def edit
    @user = User.find_by_id(params[:id])
  end

  def destroy
  end

private

  # require :user hash and permit the fileds user will submit
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    # memoization
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) 
    end

    def logged_in?
        current_user
    end

    def require_login
        unless current_user
          flash[:notice] = "Please login"
          redirect_to root_url
        end
    end

    def redirect_if_not_authorized
        if @subscription.user != current_user
            flash[:error] = "You can't make this edit, you are not the owner of this account"
            redirect_to subscription_path
        end    
    end

end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/welcome.html.erb
<h3>Welcome To Your Personal Subscription Tracker</h3>
<h3>Where You Can Keep Track Of All Your Monthly Subscriptions</h3>

<% if logged_in? %>
 <%= link_to 'Create New Subscription', new_user_subscription_path(current_user.username) %><br><br>
 <%= link_to 'See All My Subscriptions', user_subscriptions_path(current_user.username) %>
<% end %>

app/views/companies/edit.html.erb
<h1>Company#edit</h1>
<p>Find me in app/views/company/edit.html.erb</p>

app/views/companies/index.html.erb
<h1>Company#index</h1>
<p>Find me in app/views/company/index.html.erb</p>

<h1>List Of Comapanies You Have A Subscription To:</h1>

<% if @companies.length == 0 %>
        <h2>No Current Comapany Subscriptions</h2>
    <% else %>
        <% @companies.each do |s| %>
            -<%= s.name %><br>
        <% end %>   
<% end %>

app/views/companies/new.html.erb
<h1>Company#new</h1>
<p>Find me in app/views/company/new.html.erb</p>

app/views/companies/show.html.erb
<h1>Company#show</h1>
<p>Find me in app/views/company/show.html.erb</p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_errors.html.erb
<% flash.each do |type, msg| %>
    <div class="alert alert-info">
     <h3><%= msg %></h3>
    </div>
  <% end %>

app/views/layouts/all_users_subscriptions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubscriptionTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>

  <h1>Subscription Tracker</h1>
        <% if logged_in? %>             
            <%= button_to 'Logout', logout_path %>               
        <% end %>
  <br>
  <%= link_to 'See All My Subscriptions', user_subscriptions_path(current_user.username) %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubscriptionTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
      <h1>Subscription Tracker</h1>
        <% if logged_in? %>             
            <%= button_to 'Logout', logout_path %>               
        <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/create_new_subscription.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubscriptionTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>

  <h1>Subscription Tracker</h1>
        <% if logged_in? %>             
            <%= button_to 'Logout', logout_path %>               
        <% end %>
<br>    
  <%= link_to 'Create New Subscription', new_user_subscription_path(current_user.username) %><br><br>

    <%= yield %>
  </body>
</html>

app/views/subscriptions/_form.html.erb
<p>
    <%= f.label :amount_per_month %>
    <%= f.number_field :amount_per_month, step: 0.01 %>
    <br>
    <br>
    <%= f.label :type_of_subscription %>
    <%= f.text_field :type_of_subscription %>
</p>

app/views/subscriptions/_nested_form.html.erb
<%= render partial: "layouts/errors", locals: {object: company} %>

<%= f.fields_for :company do |company_builder| %>   
    <p>
        <%= company_builder.label :name %>
        <%= company_builder.text_field :name %>   
    </p>
<% end %>
<br>
<br>

app/views/subscriptions/edit.html.erb
<h1>Update Your Subscription Here</h1>

<%= render partial: "layouts/flash_errors", locals: {object: @subscription} %>

<%= form_with model: @subscription do |f| %>

    <%= render partial: "form", locals: {f: f} %>
    
    <%= render partial: "nested_form", locals: {f: f, company: @company} %>

    <%= f.submit %>
<% end %>    

app/views/subscriptions/index.html.erb
<% if current_user %>  
  <h2><%= current_user.username.upcase %>'S Current Subscriptions</h2>
<% else %>  
<h1>All Current Subscriptions</h1>
<% end %>

<% if @subscriptions.length == 0 %>
    <h2>No Current Subscriptions</h2>
    <% else %>
    <% @subscriptions.each do |s| %>
      <p>  
        Company: <%= s.company.name %></br>
        Type_of_subscription: <%= s.type_of_subscription %><br>
        Amount Per Month: $<%= s.amount_per_month %></br>
          <% if current_user == s.user %>
            <%= link_to 'edit', edit_subscription_path(s.id) %>
          <% end %>

        <%= button_to 'Delete', subscription_path(s.id), method: 'delete' %><br>
      </p>  
    <% end %>
    <br>
<% end %>

app/views/subscriptions/new.html.erb
<h1>Create New Subscription</h1>

<%= render partial: "layouts/errors", locals: {object: @subscription} %>

<%= form_for @subscription do |f| %>
  
    <%= render partial: "form", locals: {f: f} %>

    <h2>Select Name of Comapany</h2>
    <%= f.collection_select(:company_id, Company.all, :id, :name, prompt: true) %><br><br>
    
    <h3>Or Create One</h3>
    <%= render partial: "nested_form", locals: {f: f, company: @company} %>

    <%= f.submit %>  
<% end %>

app/views/subscriptions/show.html.erb
<h2>Your New Subscription Was Added To Your Account</h2>

Company: <%= @subscription.company.name %></br>
Type of Subscription: <%= @subscription.type_of_subscription %></br>
Amount Per Month: $<%= @subscription.amount_per_month %></br>
</br>
</br>
<%= button_to 'Delete', subscription_path(@subscription), method: 'delete' %><br><br>

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <br>
    <%= f.submit 'Sign Up' %>
<% end %>

<h1>Or Login</h1>
<%= button_to 'Login', login_path %>  

<h1>Or Login with Google:</h1>

<%= button_to 'Google', '/auth/google_oauth2' %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= render partial: "form" %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

    <h2>List Of All Current Users</h2>
   
    <% @users.each do |u| %>
        Username: <%= u.username %><br>
        email: <%= u.email %><br><br>
    <% end %>

app/views/users/new.html.erb
<h1> Signup Here </h1>
<%= render partial: "layouts/errors", locals: {object: @user} %>
<%= render partial: "form" %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>